### ISSUE TITLE
Latest HA update breaks integration

### ISSUE THREAD

**Issue by warmbadger** [rsnodgrass/hass-helium#11]
After updating to the latest version of HA my wallet information is no longer being reported.  Checking the logs I found these errors.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549 
First occurred: 9:54:57 AM (42 occurrences) 
Last logged: 10:01:44 AM

Entity sensor.helium_wallet_13wzmclf5vmhdezdimibdqt1srk3tvpqtjtpfmeovs2qizawzto (<class 'custom_components.helium.sensor.HeliumWalletSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.wonderful_pistachio_halibut (<class 'custom_components.helium.sensor.HeliumHotspotSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by warmbadger** [comment]
My wallet is displaying now after a few restarts, I'd close the issue but the logs requested I report the device_state_attributes issue so I'll leave it open for now

**Comment by CumpsD** [comment]
Also for HeliumPriceSensor:

```
Entity sensor.helium_hnt_oracle_price (<class 'custom_components.helium.sensor.HeliumPriceSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by rsnodgrass** [comment]
Fixed in latest release.
