### ISSUE TITLE
Add HA statistics to the integration

### ISSUE THREAD

**Issue by indexample** [rsnodgrass/hass-helium#12]
The sensors are not listed as HA statistics. Could be a cool feature!

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by rsnodgrass** [comment]
None of the device_class or state_class types seems to map to any of the sensors in this package. Feel free to contribute changes if you think there is a fit. Monetary class doesn't work for HNT, and there are no valid values that I could see which applied for the other sensors.
