### ISSUE TITLE
Manual installation issues

### ISSUE THREAD

**Issue by bhaggs** [rsnodgrass/hass-helium#2]
Any thoughts on why when manually installing the custom component that it doesn't show up in the list of available components to install from the integrations page? Is there any additional configuration done initially aside from copying the `helium` folder over to the `custom_components` folder?

**Comment by rsnodgrass** [comment]
There is no integration page or config flow support.  You install the component (either via HACS or manual copy like you did) and then edit your configuration.yaml (or an included yaml file).

**Comment by rsnodgrass** [comment]
Would be awesome if someone did write a config_flow.py so everything could be done by a UI.

**Comment by bhaggs** [comment]
Ah ok. Got it working. Thanks for making this.
