### ISSUE TITLE
Hotspotty link

### ISSUE THREAD

**Issue by dracula385** [rsnodgrass/hass-helium#21]
Hi, great helium integration. One thing, the Hotspotty link is not working for me. I think the issue it that the link has to have /status in the URL after the hotspot address. this was with ?ref=helium it just loads the initial page rather the location of my miner

**Comment by rsnodgrass** [comment]
Thanks for noticing!  Added /status so it should link directly to hotspot page.

**Comment by dracula385** [comment]
No worries... looking at the integration and the helium API there are loads more hotspot information that would be useful to get into HA, like to see hotspot activity eg. how many witnesses in some time period, beacons etc... are you considering developing the integration more in that sense... I would like to help but have limited knowledge in python and developing integrations.

Anyway thanks for the great work

**Comment by rsnodgrass** [comment]
That requires a significant database beyond the scope of Home Assistant to do all the analytics that Hotspotty (and HeliumTracker) offer, including maintaining the ETL provided by Helium on a server.  Perhaps when additional APIs open up by some of these providers, it can also be exposed via HA.
