### ISSUE TITLE
Wallet progression issues

### ISSUE THREAD

**Issue by Beiga11** [rsnodgrass/hass-helium#22]
Hi, first of all thank you for this great integration. I have been testing it for about a month and I got a couple of days with strange behavior which is the fact that there seems to be occasions where the wallet value goes down instead of up (I have not touched my wallet so far, so this should not have happened in the first place), which in turn seems to mess up the daily sensor as it cumulates the increases in the wallet but does no take in to account the decreases. Is this something related to the integration or would the issue reside in the Helium API's it might be using?

In the screenshots I am attaching you can see that since midnight the wallet growth was just 0,16 HNT (from 5,91 to 6,07), but the daily sensor reports 0,32 HNT

![image](https://user-images.githubusercontent.com/70951366/155698744-898a3900-40d4-4e38-8f19-5c44705c165f.png)

![image](https://user-images.githubusercontent.com/70951366/155698592-b69a1f32-5a4b-472c-98d4-d461beba1b39.png)

**Comment by vellanix** [comment]
I have exactly the same issue

**Comment by alexbuczynsky** [comment]
I have been having the same issue as well. In my case the value oscillates between a lower value and a higher value. This has a side effect where the COV is causing my daily HNT meter to increase with every oscillation.

This could just be problem with hotspotty reporting / caching data however, and not this integration.

**Comment by kg6zjm** [comment]
I too have been seeing this behavior. It's also on the helium price tracker sensor. 
![Screenshot_20220225-225758](https://user-images.githubusercontent.com/26174735/155833451-7b2458eb-e6bc-420c-83d6-cd30bedec838.jpg)
![Screenshot_20220225-225730](https://user-images.githubusercontent.com/26174735/155833453-8eb59a6b-cacc-445a-867e-02874a66502d.jpg)

**Comment by CumpsD** [comment]
Same here:

![image](https://user-images.githubusercontent.com/1201644/155840316-aacf5bf8-86af-4e50-ab83-e751a98ae651.png)

In reality I (sadly enough) only mined 0.20 :p

Same for overal wallet prices and helium price, weird drops constantly:

![image](https://user-images.githubusercontent.com/1201644/155840339-97756f0f-c8d3-428a-a884-23ce797cf448.png)

**Comment by alexbuczynsky** [comment]
@Beiga11 we should close this issue. The actual problem was because of the following reason which was the response in the linked issue:
> Replication was stuck on one of the follower databases. This has now been repaired and will be caught up very quickly. Thanks for your report.

**Comment by Beiga11** [comment]
Hi,

OK, it seems to be working fine again, thanks for everyone's contribution
