### ISSUE TITLE
No data for Hot Spots

### ISSUE THREAD

**Issue by mmartoccia** [rsnodgrass/hass-helium#4]
Using the below as an example, no information pertaining to this hot spot is returned. 

```
  - platform: helium
    hotspots: 
      - 148z8LXW1jqr6D7X2terBqx51tMF2mXR2w9Gu6ajQTPnYor2zsy
```

**Comment by rsnodgrass** [comment]
I've also been unable to load this hotspot by directly going to Helium
explorer:

https://explorer.helium.com/hotspots/148z8LXW1jqr6D7X2terBqx51tMF2mXR2w9Gu6ajQTPnYor2zsy/activity

This might just be an issue with the blockchain right now.

**Comment by mmartoccia** [comment]
I've found my error - thanks again for creating this integration!
