### ISSUE TITLE
Helium Price Not Updating

### ISSUE THREAD

**Issue by gittygitlab** [rsnodgrass/hass-helium#5]
After installing through HACS, I received updates to the price of HNT every few hours but after about 5 it stopped. Now it hasn't updated in 2 days.

Here's the additions I've made to the configuration.yaml file with hotspot and wallet mostly x'd out.

   - platform: helium
    hotspots: 
      - 112nosvSP1rHFiuhnh8NDC4t5EVa7gY54xxxxxxxxxxxxxxxxxxxxxx
    wallets:
      - 13dubZSbhgi5VLp8DHeUyApBZyc4Yk54xxxxxxxxxxxxxxxxxxxxxx
      

utility_meter:
  helium_wallet_today:
    source: sensor.helium_wallet_13dubZSbhgi5VLp8DHeUyApBZyc4Yk54xxxxxxxxxxxxxxxxxxxxxx
    cycle: daily

  helium_wallet_weekly:
    source: sensor.helium_wallet_13dubZSbhgi5VLp8DHeUyApBZyc4Yk54xxxxxxxxxxxxxxxxxxxxxx
    cycle: weekly

  helium_wallet_monthly:
    source: sensor.helium_wallet_13dubZSbhgi5VLp8DHeUyApBZyc4Yk54xxxxxxxxxxxxxxxxxxxxxx
    cycle: monthly

**Comment by gittygitlab** [comment]
I didn’t update anything but the issue is resolved now. Unsure the reasoning.

**Comment by rsnodgrass** [comment]
There are lots of availability and delay issues with the overlay APIs provided by Helium blockchain to read data, so there are somewhat frequent problems with data availability. Hopefully over coming months/year Helium will resolve some of these data summarization issues (these are not issues with the blockchain itself, but the summaries on top of the blockchain).
