### ISSUE TITLE
Currency Changes 

### ISSUE THREAD

**Issue by jonny190** [rsnodgrass/hass-helium#6]
Hi, is there a way to change the USD value to GBP?

**Comment by rsnodgrass** [comment]
No. Helium HNT is tied closely with USD, in fact the DC (Data Credits) are fixed to USD prices.  The Oracles are all USD.  You must use one of the exchange sensors to convert to another fiat currency.

**Comment by rsnodgrass** [comment]
FYI, I added documentation to show one way to configure other currencies (such as GBP):

https://github.com/rsnodgrass/hass-helium#is-there-a-way-to-change-fiat-currency-from-usd-to-eur-gbp-cad-etc
